### ISSUE TITLE
State of the art

### ISSUE THREAD

**Issue by vladinator1000** [jplhomer/vite-streaming-ssr-demo#4]
Hi @jplhomer, I recently started working on a [Vite plugin](https://github.com/vladinator1000/pages-ssr-apollo) that loads the "app end to end" in [Pages advanced mode](https://developers.cloudflare.com/pages/functions/advanced-mode/) with hot reloading, SSR and data fetching.

I wanted to ask, what is your impression of the Workers + React + SSR combination? Did you end up using this technology further? I'm making slow progress, but suspense, lazy loading, data loading and SSR are tricky to get right.

**Comment by jplhomer** [comment]
Hey @vladinator1000 my experience with it has been almost exclusively using https://remix.run/ which has a really nice Pages and Cloudflare adapter. The SSR, suspense, and hot reload stuff supported by the Remix Vite plugin works really well, and that's what I would probably use these days if I wanted to build a React application on Workers!
